/**
 * Simulated taste graph used when QLOO_MODE=mock (development without an API key).
 * Entity names are real public artists/brands/shows so the demo reads naturally, but every
 * affinity, popularity and venue below is SIMULATED and labelled as such in the UI.
 */

export const DIMS = ["indie", "psych", "country", "electronic", "hiphop", "latin", "soul", "pop", "rock"] as const;
export type Dim = (typeof DIMS)[number];
export type Profile = Partial<Record<Dim, number>>;

export interface MockEntity {
  name: string;
  popularity: number;
  profile: Profile;
  category?: string;
  description?: string;
}

export const ARTISTS: MockEntity[] = [
  { name: "Khruangbin", popularity: 0.82, profile: { psych: 0.9, soul: 0.8, indie: 0.7, latin: 0.3, rock: 0.3 }, description: "Houston trio blending global funk, surf and psychedelic soul." },
  { name: "Phoebe Bridgers", popularity: 0.86, profile: { indie: 1, pop: 0.4, country: 0.25, rock: 0.3 }, description: "Los Angeles singer-songwriter known for confessional indie rock." },
  { name: "Tyler Childers", popularity: 0.8, profile: { country: 1, rock: 0.4, indie: 0.3, soul: 0.2 }, description: "Kentucky songwriter rooted in Appalachian country and bluegrass." },
  { name: "Fred again..", popularity: 0.84, profile: { electronic: 1, pop: 0.5, indie: 0.3, hiphop: 0.2 }, description: "London producer turning field recordings into club music." },
  { name: "Bad Bunny", popularity: 0.97, profile: { latin: 1, hiphop: 0.6, pop: 0.7, electronic: 0.2 }, description: "Puerto Rican superstar of reggaeton and Latin trap." },
  { name: "Kendrick Lamar", popularity: 0.95, profile: { hiphop: 1, soul: 0.5, pop: 0.3 }, description: "Compton rapper and Pulitzer Prize winner." },
  { name: "Hermanos Gutiérrez", popularity: 0.55, profile: { psych: 0.7, latin: 0.6, soul: 0.4, indie: 0.4 } },
  { name: "Men I Trust", popularity: 0.6, profile: { indie: 0.8, soul: 0.5, electronic: 0.3, psych: 0.3 } },
  { name: "Mdou Moctar", popularity: 0.42, profile: { psych: 0.9, rock: 0.6, indie: 0.4 } },
  { name: "Altın Gün", popularity: 0.48, profile: { psych: 0.9, rock: 0.4, soul: 0.3, latin: 0.2 } },
  { name: "L'Impératrice", popularity: 0.52, profile: { soul: 0.6, electronic: 0.5, pop: 0.5, indie: 0.4 } },
  { name: "Yussef Dayes", popularity: 0.44, profile: { soul: 0.9, electronic: 0.3, hiphop: 0.3, psych: 0.3 } },
  { name: "Toro y Moi", popularity: 0.56, profile: { indie: 0.6, electronic: 0.5, soul: 0.5, psych: 0.4 } },
  { name: "Thee Sacred Souls", popularity: 0.4, profile: { soul: 0.95, latin: 0.3, indie: 0.2 } },
  { name: "Durand Jones & The Indications", popularity: 0.36, profile: { soul: 0.9, indie: 0.2 } },
  { name: "Lucy Dacus", popularity: 0.6, profile: { indie: 0.95, rock: 0.4, country: 0.2 } },
  { name: "Japanese Breakfast", popularity: 0.64, profile: { indie: 0.9, pop: 0.5, electronic: 0.2 } },
  { name: "Big Thief", popularity: 0.62, profile: { indie: 0.95, country: 0.35, rock: 0.3, psych: 0.2 } },
  { name: "Waxahatchee", popularity: 0.5, profile: { indie: 0.8, country: 0.6 } },
  { name: "MUNA", popularity: 0.55, profile: { indie: 0.7, pop: 0.7 } },
  { name: "Sierra Ferrell", popularity: 0.42, profile: { country: 0.9, soul: 0.2, indie: 0.3 } },
  { name: "Charley Crockett", popularity: 0.55, profile: { country: 0.9, soul: 0.4, rock: 0.2 } },
  { name: "Colter Wall", popularity: 0.5, profile: { country: 0.95, rock: 0.2 } },
  { name: "Jason Isbell", popularity: 0.66, profile: { country: 0.8, rock: 0.5, indie: 0.3 } },
  { name: "Zach Bryan", popularity: 0.88, profile: { country: 0.9, rock: 0.3, pop: 0.3 } },
  { name: "Four Tet", popularity: 0.6, profile: { electronic: 0.95, indie: 0.4, psych: 0.2 } },
  { name: "Bicep", popularity: 0.6, profile: { electronic: 0.95, pop: 0.2 } },
  { name: "Overmono", popularity: 0.46, profile: { electronic: 0.95, hiphop: 0.2 } },
  { name: "Jamie xx", popularity: 0.66, profile: { electronic: 0.85, pop: 0.35, indie: 0.4 } },
  { name: "Ross From Friends", popularity: 0.38, profile: { electronic: 0.9, indie: 0.3 } },
  { name: "Rauw Alejandro", popularity: 0.78, profile: { latin: 0.9, pop: 0.6, electronic: 0.3 } },
  { name: "Young Miko", popularity: 0.52, profile: { latin: 0.8, hiphop: 0.5, pop: 0.4 } },
  { name: "Tainy", popularity: 0.5, profile: { latin: 0.8, electronic: 0.5, hiphop: 0.3 } },
  { name: "Mon Laferte", popularity: 0.55, profile: { latin: 0.7, rock: 0.4, soul: 0.3 } },
  { name: "Vince Staples", popularity: 0.6, profile: { hiphop: 0.9, electronic: 0.2 } },
  { name: "Little Simz", popularity: 0.55, profile: { hiphop: 0.85, soul: 0.4 } },
  { name: "Noname", popularity: 0.45, profile: { hiphop: 0.7, soul: 0.6, indie: 0.2 } },
  { name: "Anderson .Paak", popularity: 0.72, profile: { soul: 0.8, hiphop: 0.6, pop: 0.3 } },
];

export const BRANDS: MockEntity[] = [
  { name: "Liquid Death", popularity: 0.62, category: "beverage", profile: { indie: 0.6, rock: 0.7, psych: 0.4, electronic: 0.2 } },
  { name: "Topo Chico", popularity: 0.6, category: "beverage", profile: { latin: 0.5, country: 0.5, indie: 0.5, psych: 0.4 } },
  { name: "Athletic Brewing", popularity: 0.45, category: "beverage", profile: { indie: 0.5, country: 0.4, rock: 0.3 } },
  { name: "Modelo", popularity: 0.8, category: "beverage", profile: { latin: 0.8, country: 0.5, hiphop: 0.3 } },
  { name: "Red Bull", popularity: 0.9, category: "beverage", profile: { electronic: 0.8, hiphop: 0.6, pop: 0.4 } },
  { name: "Olipop", popularity: 0.48, category: "beverage", profile: { indie: 0.6, pop: 0.6 } },
  { name: "Jarritos", popularity: 0.5, category: "beverage", profile: { latin: 0.9, psych: 0.3, soul: 0.3 } },
  { name: "Mezcal Vago", popularity: 0.25, category: "beverage", profile: { latin: 0.6, psych: 0.6, soul: 0.5, indie: 0.4 } },
  { name: "Patagonia", popularity: 0.75, category: "apparel", profile: { indie: 0.7, country: 0.5, psych: 0.5 } },
  { name: "Carhartt WIP", popularity: 0.6, category: "apparel", profile: { hiphop: 0.6, indie: 0.6, electronic: 0.5 } },
  { name: "Wrangler", popularity: 0.65, category: "apparel", profile: { country: 1, rock: 0.3 } },
  { name: "Levi's", popularity: 0.85, category: "apparel", profile: { rock: 0.6, country: 0.5, indie: 0.5, soul: 0.3 } },
  { name: "Nike", popularity: 0.97, category: "apparel", profile: { hiphop: 0.9, pop: 0.6, latin: 0.4 } },
  { name: "Adidas Originals", popularity: 0.85, category: "apparel", profile: { electronic: 0.6, hiphop: 0.7, latin: 0.5 } },
  { name: "Stüssy", popularity: 0.55, category: "apparel", profile: { hiphop: 0.6, electronic: 0.5, indie: 0.3 } },
  { name: "Vans", popularity: 0.75, category: "apparel", profile: { indie: 0.6, rock: 0.7, psych: 0.3 } },
  { name: "Fender", popularity: 0.7, category: "instruments", profile: { rock: 0.9, country: 0.6, indie: 0.6, psych: 0.5 } },
  { name: "Teenage Engineering", popularity: 0.35, category: "instruments", profile: { electronic: 0.9, indie: 0.4 } },
  { name: "Polaroid", popularity: 0.55, category: "lifestyle", profile: { indie: 0.7, pop: 0.4, psych: 0.3 } },
  { name: "Aesop", popularity: 0.5, category: "lifestyle", profile: { indie: 0.6, soul: 0.4, electronic: 0.3 } },
  { name: "YETI", popularity: 0.65, category: "lifestyle", profile: { country: 0.9, rock: 0.3 } },
  { name: "Ace Hotel", popularity: 0.4, category: "travel", profile: { indie: 0.8, soul: 0.5, psych: 0.5 } },
  { name: "Fenty Beauty", popularity: 0.8, category: "beauty", profile: { pop: 0.8, hiphop: 0.6, latin: 0.3 } },
  { name: "Glossier", popularity: 0.6, category: "beauty", profile: { pop: 0.7, indie: 0.5 } },
  { name: "Sonos", popularity: 0.6, category: "audio", profile: { electronic: 0.5, indie: 0.5, soul: 0.5 } },
  { name: "Tecate", popularity: 0.6, category: "beverage", profile: { latin: 0.8, rock: 0.3, country: 0.3 } },
];

export const PODCASTS: MockEntity[] = [
  { name: "Song Exploder", popularity: 0.6, profile: { indie: 0.8, pop: 0.5, electronic: 0.3 } },
  { name: "Switched on Pop", popularity: 0.5, profile: { pop: 0.9, latin: 0.3 } },
  { name: "Broken Record", popularity: 0.55, profile: { rock: 0.6, hiphop: 0.5, soul: 0.5 } },
  { name: "Popcast", popularity: 0.5, profile: { pop: 0.6, hiphop: 0.5, indie: 0.5 } },
  { name: "Questlove Supreme", popularity: 0.5, profile: { soul: 0.9, hiphop: 0.7 } },
  { name: "Dissect", popularity: 0.45, profile: { hiphop: 1, soul: 0.3 } },
  { name: "99% Invisible", popularity: 0.7, profile: { indie: 0.7, electronic: 0.4, psych: 0.3 } },
  { name: "Radiolab", popularity: 0.7, profile: { indie: 0.6, psych: 0.3 } },
  { name: "Cocaine & Rhinestones", popularity: 0.35, profile: { country: 0.95, rock: 0.3 } },
  { name: "The Bluegrass Situation", popularity: 0.25, profile: { country: 0.85, indie: 0.3 } },
  { name: "Resident Advisor Exchange", popularity: 0.3, profile: { electronic: 0.95 } },
  { name: "Radio Ambulante", popularity: 0.45, profile: { latin: 0.9, indie: 0.3 } },
  { name: "Tiny Desk Concerts", popularity: 0.75, profile: { indie: 0.7, soul: 0.7, latin: 0.3, psych: 0.3 } },
  { name: "Anything Goes", popularity: 0.6, profile: { pop: 0.7, indie: 0.4 } },
  { name: "Sound Opinions", popularity: 0.4, profile: { rock: 0.8, indie: 0.6, psych: 0.4 } },
  { name: "Las Culturistas", popularity: 0.55, profile: { pop: 0.8 } },
];

export const TV_SHOWS: MockEntity[] = [
  { name: "The Bear", popularity: 0.85, profile: { indie: 0.7, soul: 0.5, rock: 0.3 } },
  { name: "Atlanta", popularity: 0.75, profile: { hiphop: 0.8, soul: 0.6, psych: 0.3 } },
  { name: "Yellowstone", popularity: 0.88, profile: { country: 1 } },
  { name: "Euphoria", popularity: 0.85, profile: { pop: 0.7, electronic: 0.6, hiphop: 0.5 } },
  { name: "Reservation Dogs", popularity: 0.55, profile: { indie: 0.7, country: 0.4, rock: 0.3 } },
  { name: "Twin Peaks", popularity: 0.6, profile: { psych: 0.8, indie: 0.7 } },
  { name: "Severance", popularity: 0.8, profile: { indie: 0.6, electronic: 0.5 } },
  { name: "Insecure", popularity: 0.65, profile: { hiphop: 0.6, soul: 0.8 } },
  { name: "Narcos: Mexico", popularity: 0.7, profile: { latin: 0.8, hiphop: 0.3 } },
  { name: "Los Espookys", popularity: 0.35, profile: { latin: 0.7, indie: 0.6, psych: 0.4 } },
  { name: "Industry", popularity: 0.5, profile: { electronic: 0.7, pop: 0.5 } },
  { name: "Fargo", popularity: 0.7, profile: { country: 0.5, indie: 0.5, rock: 0.3 } },
  { name: "The White Lotus", popularity: 0.85, profile: { pop: 0.6, indie: 0.5 } },
  { name: "Station Eleven", popularity: 0.45, profile: { indie: 0.8, psych: 0.4 } },
  { name: "Top Boy", popularity: 0.55, profile: { hiphop: 0.8, electronic: 0.5 } },
];

export const TAGS: { id: string; name: string; profile: Profile }[] = [
  { id: "urn:tag:genre:music:psychedelic_rock", name: "Psychedelic Rock", profile: { psych: 1, rock: 0.5 } },
  { id: "urn:tag:genre:music:funk", name: "Funk", profile: { soul: 0.8, psych: 0.4, hiphop: 0.3 } },
  { id: "urn:tag:genre:music:neo_soul", name: "Neo-Soul", profile: { soul: 1, hiphop: 0.4 } },
  { id: "urn:tag:genre:music:indie_folk", name: "Indie Folk", profile: { indie: 0.9, country: 0.4 } },
  { id: "urn:tag:genre:music:dream_pop", name: "Dream Pop", profile: { indie: 0.8, pop: 0.4, electronic: 0.3 } },
  { id: "urn:tag:genre:music:americana", name: "Americana", profile: { country: 0.9, rock: 0.4, indie: 0.3 } },
  { id: "urn:tag:genre:music:outlaw_country", name: "Outlaw Country", profile: { country: 1, rock: 0.4 } },
  { id: "urn:tag:genre:music:house", name: "House", profile: { electronic: 1, pop: 0.2 } },
  { id: "urn:tag:genre:music:uk_garage", name: "UK Garage", profile: { electronic: 0.9, hiphop: 0.3 } },
  { id: "urn:tag:genre:music:reggaeton", name: "Reggaeton", profile: { latin: 1, pop: 0.5, hiphop: 0.4 } },
  { id: "urn:tag:genre:music:conscious_hip_hop", name: "Conscious Hip Hop", profile: { hiphop: 1, soul: 0.5 } },
  { id: "urn:tag:genre:music:surf_rock", name: "Surf Rock", profile: { psych: 0.6, rock: 0.6, indie: 0.3 } },
  { id: "urn:tag:lifestyle:vinyl_collecting", name: "Vinyl Collecting", profile: { soul: 0.6, psych: 0.6, indie: 0.6, rock: 0.4 } },
  { id: "urn:tag:lifestyle:natural_wine", name: "Natural Wine", profile: { indie: 0.7, electronic: 0.3, soul: 0.3 } },
  { id: "urn:tag:lifestyle:thrifting", name: "Thrifting", profile: { indie: 0.7, psych: 0.4, pop: 0.3 } },
  { id: "urn:tag:lifestyle:hiking", name: "Hiking", profile: { country: 0.6, indie: 0.5 } },
  { id: "urn:tag:lifestyle:craft_beer", name: "Craft Beer", profile: { rock: 0.5, country: 0.5, indie: 0.4 } },
  { id: "urn:tag:lifestyle:specialty_coffee", name: "Specialty Coffee", profile: { indie: 0.7, electronic: 0.3 } },
  { id: "urn:tag:lifestyle:festival_culture", name: "Festival Culture", profile: { electronic: 0.7, psych: 0.5, pop: 0.4 } },
  { id: "urn:tag:lifestyle:skateboarding", name: "Skateboarding", profile: { rock: 0.5, hiphop: 0.5, indie: 0.3 } },
  { id: "urn:tag:lifestyle:mezcal", name: "Mezcal & Agave", profile: { latin: 0.7, psych: 0.4, soul: 0.4 } },
  { id: "urn:tag:lifestyle:film_photography", name: "Film Photography", profile: { indie: 0.8, psych: 0.3 } },
  { id: "urn:tag:lifestyle:streetwear", name: "Streetwear", profile: { hiphop: 0.9, electronic: 0.4, latin: 0.4 } },
  { id: "urn:tag:lifestyle:record_stores", name: "Record Stores", profile: { soul: 0.6, psych: 0.6, indie: 0.6 } },
  { id: "urn:tag:lifestyle:bbq", name: "Barbecue", profile: { country: 0.8, soul: 0.4 } },
  { id: "urn:tag:lifestyle:camping", name: "Camping", profile: { country: 0.7, indie: 0.4, psych: 0.3 } },
  { id: "urn:tag:lifestyle:late_night_clubbing", name: "Late-Night Clubbing", profile: { electronic: 1, latin: 0.4, hiphop: 0.4 } },
  { id: "urn:tag:lifestyle:tacos", name: "Taquerias", profile: { latin: 0.7, psych: 0.3, country: 0.3 } },
];

export const BRAND_CATEGORY_TAGS: { id: string; name: string; category: string; keywords: string[] }[] = [
  { id: "urn:tag:category:brand:beverage", name: "Beverages", category: "beverage", keywords: ["beverage", "drink", "drinks", "beer", "soda", "water", "spirits"] },
  { id: "urn:tag:category:brand:apparel", name: "Apparel", category: "apparel", keywords: ["apparel", "fashion", "clothing", "streetwear", "merch"] },
  { id: "urn:tag:category:brand:instruments", name: "Musical Instruments", category: "instruments", keywords: ["instrument", "instruments", "guitar", "gear"] },
  { id: "urn:tag:category:brand:lifestyle", name: "Lifestyle", category: "lifestyle", keywords: ["lifestyle", "outdoor"] },
  { id: "urn:tag:category:brand:beauty", name: "Beauty", category: "beauty", keywords: ["beauty", "cosmetics", "skincare"] },
  { id: "urn:tag:category:brand:audio", name: "Audio", category: "audio", keywords: ["audio", "headphones", "speakers"] },
  { id: "urn:tag:category:brand:travel", name: "Travel & Hotels", category: "travel", keywords: ["travel", "hotel", "hotels"] },
];

/** City taste leanings (simulated). Missing dims fall back to a neutral baseline. */
export const CITY_PROFILES: Record<string, Profile> = {
  "New York": { indie: 0.7, hiphop: 0.8, electronic: 0.6, soul: 0.6, latin: 0.6, pop: 0.7 },
  "Los Angeles": { indie: 0.7, hiphop: 0.8, latin: 0.8, pop: 0.8, psych: 0.6 },
  Chicago: { hiphop: 0.7, electronic: 0.7, soul: 0.7, indie: 0.6 },
  Dallas: { country: 0.7, hiphop: 0.6, latin: 0.6, pop: 0.6 },
  Houston: { hiphop: 0.8, latin: 0.7, country: 0.6, soul: 0.6, psych: 0.5 },
  Washington: { hiphop: 0.6, soul: 0.7, indie: 0.5 },
  Philadelphia: { hiphop: 0.7, soul: 0.7, indie: 0.6, rock: 0.5 },
  Miami: { latin: 1, electronic: 0.8, hiphop: 0.7, pop: 0.7 },
  Atlanta: { hiphop: 1, soul: 0.7, pop: 0.5 },
  Boston: { indie: 0.7, rock: 0.6, pop: 0.5 },
  Phoenix: { country: 0.6, latin: 0.6, rock: 0.5 },
  "San Francisco": { indie: 0.7, electronic: 0.7, psych: 0.7, soul: 0.5 },
  Seattle: { indie: 0.8, rock: 0.7, psych: 0.5, electronic: 0.5 },
  Minneapolis: { indie: 0.7, soul: 0.6, rock: 0.6 },
  "San Diego": { psych: 0.6, latin: 0.6, rock: 0.6, indie: 0.5 },
  Denver: { psych: 0.85, indie: 0.7, country: 0.6, electronic: 0.6, rock: 0.6 },
  Portland: { indie: 0.9, psych: 0.7, soul: 0.5, country: 0.4 },
  Austin: { psych: 0.85, indie: 0.8, country: 0.7, soul: 0.6, latin: 0.5 },
  Nashville: { country: 1, rock: 0.6, indie: 0.5, soul: 0.4 },
  "New Orleans": { soul: 0.95, psych: 0.6, hiphop: 0.6 },
  "Salt Lake City": { indie: 0.6, electronic: 0.5, country: 0.5 },
  Asheville: { indie: 0.85, psych: 0.8, country: 0.75, soul: 0.5 },
  Boulder: { psych: 0.8, indie: 0.8, country: 0.6, electronic: 0.5 },
  Toronto: { hiphop: 0.8, indie: 0.6, electronic: 0.6, pop: 0.6 },
  Montreal: { indie: 0.8, electronic: 0.7, soul: 0.4 },
  Vancouver: { indie: 0.7, electronic: 0.6, psych: 0.5 },
  London: { electronic: 0.9, hiphop: 0.7, indie: 0.7, soul: 0.7, pop: 0.7 },
  Paris: { electronic: 0.8, soul: 0.7, hiphop: 0.7, pop: 0.6 },
  Madrid: { latin: 0.8, pop: 0.7, electronic: 0.5 },
  Barcelona: { electronic: 0.85, latin: 0.7, indie: 0.6, psych: 0.5 },
  Berlin: { electronic: 1, indie: 0.6, psych: 0.5 },
  Milan: { pop: 0.7, electronic: 0.6, hiphop: 0.5 },
  Rome: { pop: 0.7, rock: 0.5, soul: 0.4 },
  Hamburg: { indie: 0.6, electronic: 0.7, rock: 0.6 },
  Lisbon: { soul: 0.7, latin: 0.6, psych: 0.6, indie: 0.5 },
  Manchester: { indie: 0.8, electronic: 0.8, rock: 0.7 },
  Amsterdam: { electronic: 0.9, psych: 0.8, soul: 0.6, indie: 0.6 },
  Stockholm: { pop: 0.8, electronic: 0.7, indie: 0.6 },
  Brussels: { electronic: 0.7, hiphop: 0.6, soul: 0.5 },
  Vienna: { electronic: 0.6, soul: 0.6, indie: 0.5 },
  Copenhagen: { indie: 0.7, electronic: 0.7, psych: 0.5 },
  Dublin: { indie: 0.7, rock: 0.7, country: 0.5 },
  Glasgow: { indie: 0.8, rock: 0.8, electronic: 0.6 },
  Lyon: { electronic: 0.6, soul: 0.6, psych: 0.5 },
  Bristol: { electronic: 0.85, psych: 0.7, soul: 0.7, indie: 0.7 },
  Utrecht: { psych: 0.8, indie: 0.8, soul: 0.6 },
  Leipzig: { electronic: 0.85, psych: 0.7, indie: 0.7 },
  "Mexico City": { latin: 0.95, psych: 0.6, indie: 0.6, electronic: 0.6 },
  "São Paulo": { latin: 0.8, electronic: 0.7, soul: 0.6 },
  "Buenos Aires": { latin: 0.8, rock: 0.7, electronic: 0.6 },
  Bogotá: { latin: 0.9, electronic: 0.6 },
  Santiago: { latin: 0.8, indie: 0.6, rock: 0.6 },
  Guadalajara: { latin: 0.9, indie: 0.6, psych: 0.5 },
  Medellín: { latin: 1, electronic: 0.6, hiphop: 0.5 },
  "San Juan": { latin: 1, hiphop: 0.7, pop: 0.6 },
  Tokyo: { electronic: 0.7, indie: 0.7, pop: 0.7, soul: 0.6 },
  Seoul: { pop: 0.9, hiphop: 0.7, electronic: 0.6 },
  Osaka: { pop: 0.7, rock: 0.6, indie: 0.5 },
  Manila: { pop: 0.8, indie: 0.5, soul: 0.5 },
  Bangkok: { pop: 0.7, psych: 0.6, electronic: 0.5 },
  Jakarta: { pop: 0.8, indie: 0.6 },
  Singapore: { electronic: 0.7, pop: 0.7, indie: 0.5 },
  Sydney: { indie: 0.7, electronic: 0.7, psych: 0.6 },
  Melbourne: { indie: 0.8, psych: 0.8, soul: 0.6, electronic: 0.6 },
  Auckland: { indie: 0.6, soul: 0.6, rock: 0.5 },
};

export const PLACE_KINDS = [
  { subtype: "bar", label: "Cocktail bar", words: ["Lounge", "Room", "Social", "Tavern", "Bar"] },
  { subtype: "restaurant", label: "Restaurant", words: ["Kitchen", "Cantina", "Table", "Diner", "Eatery"] },
  { subtype: "record_store", label: "Record store", words: ["Records", "Vinyl", "Sound Shop", "Wax"] },
  { subtype: "cafe", label: "Coffee shop", words: ["Coffee", "Roasters", "Café"] },
  { subtype: "music_venue", label: "Listening bar", words: ["Hi-Fi", "Listening Room", "Audio Club"] },
] as const;

export const PLACE_ADJECTIVES = [
  "Golden", "Velvet", "Electric", "Midnight", "Copper", "Paper Moon", "Wild", "Blue Hour",
  "Second Story", "Northside", "Lantern", "Orchard", "Cosmic", "Low Tide", "Saint", "Echo",
];
